STOP_WORDS: frozenset[str] = frozenset({
    # ── English (~175) ──────────────────────────────────────────────────
    "a", "about", "above", "after", "again", "against", "all", "am", "an",
    "and", "any", "are", "aren't", "as", "at", "be", "because", "been",
    "before", "being", "below", "between", "both", "but", "by", "can",
    "can't", "cannot", "could", "couldn't", "did", "didn't", "do", "does",
    "doesn't", "doing", "don't", "down", "during", "each", "few", "for",
    "from", "further", "get", "got", "had", "hadn't", "has", "hasn't",
    "have", "haven't", "having", "he", "he'd", "he'll", "he's", "her",
    "here", "here's", "hers", "herself", "him", "himself", "his", "how",
    "how's", "i", "i'd", "i'll", "i'm", "i've", "if", "in", "into", "is",
    "isn't", "it", "it's", "its", "itself", "just", "let's", "me", "might",
    "more", "most", "mustn't", "my", "myself", "no", "nor", "not", "of",
    "off", "on", "once", "only", "or", "other", "ought", "our", "ours",
    "ourselves", "out", "over", "own", "same", "shan't", "she", "she'd",
    "she'll", "she's", "should", "shouldn't", "so", "some", "such", "than",
    "that", "that's", "the", "their", "theirs", "them", "themselves", "then",
    "there", "there's", "these", "they", "they'd", "they'll", "they're",
    "they've", "this", "those", "through", "to", "too", "under", "until",
    "up", "us", "very", "was", "wasn't", "we", "we'd", "we'll", "we're",
    "we've", "were", "weren't", "what", "what's", "when", "when's", "where",
    "where's", "which", "while", "who", "who's", "whom", "why", "why's",
    "will", "with", "won't", "would", "wouldn't", "you", "you'd", "you'll",
    "you're", "you've", "your", "yours", "yourself", "yourselves",
    # ── German (~175) ───────────────────────────────────────────────────
    "aber", "alle", "allem", "allen", "aller", "allerdings", "alles", "also",
    "am", "an", "ander", "andere", "anderem", "anderen", "anderer", "anderes",
    "anderm", "andern", "anders", "auch", "auf", "aus", "bei", "beim",
    "bereits", "bin", "bis", "bist", "bitte", "da", "dabei", "dadurch",
    "dafür", "dagegen", "daher", "dahin", "damals", "damit", "danach",
    "daneben", "dann", "daran", "darauf", "daraus", "darf", "darfst",
    "darin", "darum", "darunter", "darüber", "das", "dass", "davon",
    "davor", "dazu", "dein", "deine", "deinem", "deinen", "deiner",
    "dem", "den", "denn", "dennoch", "der", "deren", "des", "deshalb",
    "dessen", "dich", "die", "dies", "diese", "dieselbe", "dieselben",
    "diesem", "diesen", "dieser", "dieses", "doch", "dort", "du", "dumm",
    "durch", "dürfen", "ein", "einander", "eine", "einem", "einen",
    "einer", "einige", "einigem", "einigen", "einiger", "einiges",
    "einmal", "er", "erst", "es", "etwa", "etwas", "euch", "euer",
    "eure", "eurem", "euren", "eurer", "für", "ganz", "gar", "gegen",
    "gehen", "gern", "gewesen", "gewiß", "groß", "große", "großem",
    "großen", "großer", "großes", "gut", "guten", "guter", "gutes",
    "habe", "haben", "habt", "hat", "hatte", "hätte", "hier", "hin",
    "hinter", "ich", "ihm", "ihn", "ihnen", "ihr", "ihre", "ihrem",
    "ihren", "ihrer", "immer", "in", "indem", "infolge", "innen",
    "ins", "irgend", "ist", "ja", "jede", "jedem", "jeden", "jeder",
    "jedes", "jedoch", "jemals", "jene", "jenem", "jenen", "jener",
    "jenes", "jetzt", "kann", "kannst", "kein", "keine", "keinem",
    "keinen", "keiner", "kommen", "konnte", "können", "künftig",
    "lang", "lange", "längst", "längstens", "lassen", "lässt",
    "machen", "man", "manch", "manche", "manchem", "manchen",
    "mancher", "manchmal", "mehr", "mein", "meine", "meinem",
    "meinen", "meiner", "mit", "muss", "müssen", "nach", "nachdem",
    "nachher", "nächst", "neben", "nein", "nicht", "nichts", "nie",
    "niemand", "noch", "nun", "nur", "ob", "oben", "oder", "ohne",
    "schon", "sehr", "seid", "sein", "seine", "seinem", "seinen",
    "seiner", "seit", "seitdem", "sich", "sie", "sind", "so", "sogar",
    "solch", "solche", "solchem", "solchen", "solcher", "soll",
    "sollen", "sollte", "sollten", "solltest", "sondern", "sonst",
    "sowie", "über", "überall", "um", "ums", "und", "uns", "unser",
    "unsere", "unserem", "unseren", "unserer", "unten", "unter",
    "viel", "viele", "vielem", "vielen", "vielleicht", "vom", "von",
    "vor", "vorbei", "vorher", "wahrscheinlich", "wann", "war",
    "wäre", "warum", "was", "weder", "wegen", "weil", "weit",
    "weiter", "weitere", "weiterem", "weiteren", "weiterer",
    "weiteres", "welch", "welche", "welchem", "welchen", "welcher",
    "welches", "wem", "wen", "wenig", "wenige", "weniger", "wenigstens",
    "wenn", "wer", "werde", "werden", "wessen", "wie", "wieder",
    "will", "wir", "wird", "wo", "wohl", "wollen", "worden",
    "worin", "würde", "würden", "zu", "zum", "zur", "zwar",
    "zwischen",
})
